### ISSUE TITLE
希望交流一下

### ISSUE THREAD

**Issue by sssSSSay** [onlyonewater/Machine-Learing-in-MATLAB#1]
关于cladder，不知道您复现成功了没有，我的邮箱是ssaymoon@163.com

**Comment by onlyonewater** [comment]
hi, @sssSSSay, I did not re-implement the causalCoT, but I read the paper, so we can discuss the algorithm, I am new to causality.

**Comment by sssSSSay** [comment]
可以留一个联系方式吗，想跟您交流一下:D

**Comment by onlyonewater** [comment]
ok, no problem, any discussions are welcome, my e-mail address is `cs.dh97@gmail.com`
